# -*- coding: utf-8 -*-
"""lotofacil_simulador12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMGxnx9bXV6inwF-oe762df55mmadNLI
"""

import streamlit as st
import random
import pandas as pd
import collections
from datetime import datetime
import os # Para verificar a existência de arquivos

# --- CONFIGURAÇÕES DA PÁGINA ---
st.set_page_config(
    page_title="Simulador e Estatísticas Lotofácil",
    page_icon="🎲",
    layout="wide" # Layout mais amplo para acomodar mais conteúdo
)

st.title("🎲 Simulador e Estatísticas da Lotofácil")
st.write("Gere sorteios, confira seus acertos e compare com os dados oficiais da Caixa.")

# --- Nomes dos arquivos de dados CSV ---
ARQUIVO_HISTORICO_OFICIAL_CSV = 'Lotofacil.csv'
ARQUIVO_TABELA_PRECO_CSV = 'Tabela_Preco.csv'
ARQUIVO_MEUS_SIMULADOS_CSV = 'meus_jogos_simulados.csv' # Novo arquivo para histórico de simulados

# --- Inicialização do Estado da Sessão ---
# Variável para armazenar o último sorteio gerado (simulado) para possível salvamento
if 'ultimo_sorteio_gerado_simulado' not in st.session_state:
    st.session_state.ultimo_sorteio_gerado_simulado = None

# --- Funções para Carregar/Salvar Dados CSV ---

@st.cache_data(ttl=3600) # Cache por 1 hora para dados oficiais
def carregar_dados_oficiais():
    """Carrega o histórico de sorteios oficiais da Lotofácil de um CSV."""
    if os.path.exists(ARQUIVO_HISTORICO_OFICIAL_CSV):
        try:
            df = pd.read_csv(ARQUIVO_HISTORICO_OFICIAL_CSV, sep=',')

            # --- DIAGNÓSTICO: Imprime as colunas lidas do CSV no terminal ---
            print(f"Colunas lidas de {ARQUIVO_HISTORICO_OFICIAL_CSV}: {df.columns.tolist()}")
            # ------------------------------------------------------------------

            # Tenta converter a coluna 'Data Sorteio' para datetime, tratando erros
            # dayfirst=True é importante se o CSV tiver datas no formato DD/MM/YYYY
            df['Data Sorteio'] = pd.to_datetime(df['Data Sorteio'], errors='coerce', dayfirst=True)
            df.dropna(subset=['Data Sorteio'], inplace=True) # Remove linhas com data inválida (NaT)

            return df
        except Exception as e:
            st.error(f"Erro ao carregar o arquivo '{ARQUIVO_HISTORICO_OFICIAL_CSV}'. Verifique se ele está no formato CSV e as colunas estão corretas: {e}")
            return pd.DataFrame() # Retorna DataFrame vazio em caso de erro
    return pd.DataFrame()

def salvar_novo_sorteio_oficial(novo_sorteio_df):
    """Salva um novo sorteio oficial no arquivo CSV."""
    df_existente = carregar_dados_oficiais()

    # Remover do cache antes de modificar o arquivo
    st.cache_data.clear() # Limpa todos os caches de dados

    # Adiciona o novo sorteio. Usa ignore_index=True para garantir um novo índice limpo.
    df_atualizado = pd.concat([df_existente, novo_sorteio_df], ignore_index=True)
    df_atualizado.to_csv(ARQUIVO_HISTORICO_OFICIAL_CSV, index=False, sep=',')
    st.success(f"Novo concurso {novo_sorteio_df['Concurso'].iloc[0]} adicionado com sucesso!")
    st.rerun() # Recarrega a página para refletir as mudanças

@st.cache_data(ttl=3600) # Cache por 1 hora para tabela de preços
def carregar_tabela_precos():
    """Carrega a tabela de preços do jogo de um CSV."""
    if os.path.exists(ARQUIVO_TABELA_PRECO_CSV):
        try:
            df = pd.read_csv(ARQUIVO_TABELA_PRECO_CSV, sep=',')
            return df
        except Exception as e:
            st.error(f"Erro ao carregar o arquivo '{ARQUIVO_TABELA_PRECO_CSV}'. Verifique se ele está no formato CSV e as colunas estão corretas: {e}")
            return pd.DataFrame()
    return pd.DataFrame()


# --- NOVAS FUNÇÕES PARA HISTÓRICO DE JOGOS SIMULADOS ---
@st.cache_data(ttl=60) # Cache mais curto, pois será mais dinâmico
def carregar_meus_simulados():
    """Carrega o histórico de jogos simulados do usuário."""
    if os.path.exists(ARQUIVO_MEUS_SIMULADOS_CSV):
        try:
            df = pd.read_csv(ARQUIVO_MEUS_SIMULADOS_CSV, sep=',')
            # Tenta converter a coluna 'Data_Hora' para datetime
            df['Data_Hora'] = pd.to_datetime(df['Data_Hora'], errors='coerce')
            df.dropna(subset=['Data_Hora'], inplace=True)
            return df
        except Exception as e:
            st.error(f"Erro ao carregar o histórico de jogos simulados '{ARQUIVO_MEUS_SIMULADOS_CSV}': {e}")
            return pd.DataFrame(columns=['ID', 'Data_Hora'] + [f'Bola{i}' for i in range(1, 16)])
    # Se o arquivo não existe, cria um DataFrame vazio com as colunas corretas
    return pd.DataFrame(columns=['ID', 'Data_Hora'] + [f'Bola{i}' for i in range(1, 16)])

def salvar_simulado_no_historico(simulado_lista):
    """Salva um jogo simulado no histórico CSV."""
    df_existente = carregar_meus_simulados()

    novo_id = 1 if df_existente.empty else df_existente['ID'].max() + 1

    novo_registro_dict = {
        'ID': int(novo_id),
        'Data_Hora': datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
    for i, bola in enumerate(simulado_lista):
        novo_registro_dict[f'Bola{i+1}'] = bola

    novo_df = pd.DataFrame([novo_registro_dict])

    df_atualizado = pd.concat([df_existente, novo_df], ignore_index=True)
    df_atualizado.to_csv(ARQUIVO_MEUS_SIMULADOS_CSV, index=False, sep=',')
    st.cache_data.clear() # Limpa cache de simulados para recarregar
    st.success(f"Jogo simulado {novo_id} salvo no histórico!")
    st.rerun() # Recarrega para mostrar o histórico atualizado

def limpar_meus_simulados_historico():
    """Limpa o arquivo de histórico de jogos simulados."""
    if os.path.exists(ARQUIVO_MEUS_SIMULADOS_CSV):
        try:
            os.remove(ARQUIVO_MEUS_SIMULADOS_CSV)
            st.cache_data.clear() # Limpa cache de simulados
            st.success("Histórico de jogos simulados limpo com sucesso!")
        except Exception as e:
            st.error(f"Erro ao limpar histórico: {e}")
    else:
        st.info("Não há histórico de jogos simulados para limpar.")
    st.rerun()

# --- Funções Auxiliares de Estatísticas ---
def calcular_estatisticas_oficiais(df_sorteios):
    """Calcula a frequência de cada número em um DataFrame de sorteios oficiais."""
    if df_sorteios.empty:
        return pd.DataFrame({'Número': [], 'Frequência': []})

    # Coleta todas as bolas de Bola1 a Bola15
    colunas_bolas = [f'Bola{i}' for i in range(1, 16)]
    # Filtra para ter certeza que as colunas existem antes de tentar coletar
    colunas_existentes = [col for col in colunas_bolas if col in df_sorteios.columns]

    if not colunas_existentes:
        st.warning("Não foram encontradas as colunas de bolas (Bola1-Bola15) necessárias para calcular as estatísticas oficiais. Verifique a estrutura do seu CSV.")
        return pd.DataFrame({'Número': [], 'Frequência': []})

    todos_numeros_sorteados = df_sorteios[colunas_existentes].values.flatten().tolist()

    frequencia = collections.Counter(todos_numeros_sorteados)
    df_frequencia = pd.DataFrame(frequencia.items(), columns=['Número', 'Frequência'])
    df_frequencia = df_frequencia.sort_values(by='Frequência', ascending=False)
    return df_frequencia

# --- LAYOUT DA APLICAÇÃO STREAMLIT ---

# Criação de abas (tabs) para organizar o conteúdo
tab1, tab2, tab3, tab4 = st.tabs(["Simulador e Meus Jogos", "Estatísticas Oficiais", "Inserir Concurso Oficial", "Tabela de Preços"])

# --- ABA 1: Simulador e Meus Jogos ---
with tab1:
    st.header("Gerar Novo Sorteio Simulado")
    if st.button("Sortear Números"):
        novo_sorteio_simulado = random.sample(range(1, 26), 15)
        novo_sorteio_simulado.sort()
        st.session_state.ultimo_sorteio_gerado_simulado = novo_sorteio_simulado
        st.success(f"Seu sorteio atual: **{', '.join(map(str, novo_sorteio_simulado))}**")

    if st.session_state.ultimo_sorteio_gerado_simulado:
        if st.button("Salvar este Jogo no Meu Histórico", help="Salva o sorteio atual para conferência posterior"):
            salvar_simulado_no_historico(st.session_state.ultimo_sorteio_gerado_simulado)

    st.markdown("---")

    st.header("Meu Histórico de Jogos Simulados Salvos")
    df_meus_simulados = carregar_meus_simulados()

    if not df_meus_simulados.empty:
        st.write("Aqui estão os jogos simulados que você salvou:")
        # Criar uma cópia para formatação de data para exibição
        df_meus_simulados_display = df_meus_simulados.copy()
        if 'Data_Hora' in df_meus_simulados_display.columns:
             df_meus_simulados_display['Data_Hora'] = df_meus_simulados_display['Data_Hora'].dt.strftime('%d/%m/%Y %H:%M:%S').fillna('Data Inválida')

        # Selecionar colunas para exibição
        cols_to_show_simulados = ['ID', 'Data_Hora'] + [f'Bola{i}' for i in range(1, 16)]
        existing_cols_to_show_simulados = [col for col in cols_to_show_simulados if col in df_meus_simulados_display.columns]

        st.dataframe(df_meus_simulados_display[existing_cols_to_show_simulados], use_container_width=True)

        if st.button("Limpar Histórico de Jogos Simulados Salvos", key="limpar_meus_simulados"):
            limpar_meus_simulados_historico()
    else:
        st.info("Nenhum jogo simulado salvo ainda. Gere um jogo e clique em 'Salvar este Jogo no Meu Histórico'.")

    st.markdown("---")

    # --- Conferência de Jogo com Histórico Salvo ---
    st.header("Conferir Meus Jogos Simulados com Números Oficiais")
    if not df_meus_simulados.empty:
        with st.form("form_conferencia_jogo_historico"):
            st.write("Insira os 15 números oficiais sorteados pela Caixa (separados por vírgula ou espaço):")
            numeros_oficiais_str = st.text_input(
                "Números Oficiais (ex: 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 24, 25)",
                key="numeros_oficiais_historico_input"
            )
            conferir_button = st.form_submit_button("Conferir Acertos de Todos os Jogos Salvos")

            if conferir_button:
                try:
                    oficiais_lista = [int(n.strip()) for n in numeros_oficiais_str.replace(',', ' ').split() if n.strip().isdigit()]

                    if len(set(oficiais_lista)) != 15:
                        st.error("Por favor, insira exatamente 15 números únicos para os números oficiais.")
                    elif not all(1 <= num <= 25 for num in oficiais_lista):
                        st.error("Os números oficiais devem estar entre 1 e 25.")
                    else:
                        oficiais_set = set(oficiais_lista)
                        st.subheader("Resultados da Conferência:")

                        colunas_bolas = [f'Bola{i}' for i in range(1, 16)]
                        for index, row in df_meus_simulados.iterrows():
                            # Converte a lista de bolas da linha para um set
                            jogo_simulado_da_linha = set(row[colunas_bolas].tolist())

                            acertos = jogo_simulado_da_linha.intersection(oficiais_set)

                            st.markdown(f"**Jogo ID {int(row['ID'])} (em {row['Data_Hora'].strftime('%d/%m/%Y %H:%M:%S')}):**")
                            st.write(f"   Seu Jogo: {', '.join(map(str, sorted(list(jogo_simulado_da_linha))))}")
                            st.write(f"   Acertos: **{len(acertos)}** números")
                            if len(acertos) > 0:
                                st.write(f"   Números acertados: {', '.join(map(str, sorted(list(acertos))))}")
                            st.markdown("---")

                except ValueError:
                    st.error("Por favor, insira os números oficiais em um formato válido (apenas números separados por vírgulas ou espaços).")
    else:
        st.info("Salve alguns jogos simulados para poder conferir seus acertos.")


# --- ABA 2: Estatísticas Oficiais ---
with tab2:
    st.header("Estatística: Números Oficiais da Caixa")
    df_oficial = carregar_dados_oficiais() # Carrega os dados oficiais (usando cache)

    if not df_oficial.empty:
        st.subheader("Histórico Completo de Sorteios Oficiais")

        # --- AJUSTE: Filtra as colunas para exibição, pegando apenas as que existem ---
        expected_cols = ['Concurso', 'Data Sorteio'] + [f'Bola{i}' for i in range(1, 16)]
        existing_cols_to_display = [col for col in expected_cols if col in df_oficial.columns]

        # Formata 'Data Sorteio' para exibição (DD/MM/AAAA)
        df_display = df_oficial.copy() # Cria uma cópia para não alterar o DataFrame original
        if 'Data Sorteio' in df_display.columns:
            # Garante que é datetime antes de formatar, e lida com NaT
            df_display['Data Sorteio'] = df_display['Data Sorteio'].dt.strftime('%d/%m/%Y').fillna('Data Inválida') # <-- CORREÇÃO AQUI

        if existing_cols_to_display:
            st.dataframe(df_display[existing_cols_to_display], use_container_width=True)
        else:
            st.warning("Nenhuma das colunas esperadas ('Concurso', 'Data Sorteio', 'Bola1'...'Bola15') foi encontrada no arquivo CSV oficial para exibição. Verifique os cabeçalhos do seu arquivo.")
        # -----------------------------------------------------------------------------

        st.subheader("Frequência dos Números Oficiais")
        df_estatisticas_oficiais = calcular_estatisticas_oficiais(df_oficial)

        if not df_estatisticas_oficiais.empty:
            st.write("Frequência de cada número nos sorteios oficiais:")
            st.dataframe(df_estatisticas_oficiais, use_container_width=True)
            st.subheader("Gráfico de Frequência de Oficiais")
            st.bar_chart(df_estatisticas_oficiais.set_index('Número'))
            st.info(f"Total de concursos oficiais carregados: {len(df_oficial)}")
        else:
            st.warning("Não foi possível calcular as estatísticas dos números oficiais. Verifique a estrutura das colunas 'Bola1'...'Bola15' no seu CSV.")
    else:
        st.warning(f"Arquivo '{ARQUIVO_HISTORICO_OFICIAL_CSV}' não encontrado ou vazio. Por favor, adicione um arquivo CSV com o histórico de sorteios oficiais ou insira novos concursos na aba 'Inserir Concurso Oficial'.")

# --- ABA 3: Inserir Concurso Oficial ---
with tab3:
    st.header("Adicionar Novo Concurso Oficial da Caixa")
    st.write("Preencha os campos abaixo para adicionar um novo resultado de concurso oficial.")

    with st.form("form_novo_concurso"):
        col1, col2 = st.columns(2)
        with col1:
            concurso = st.number_input("Número do Concurso", min_value=1, step=1, key="concurso_input")
        with col2:
            data_sorteio = st.date_input("Data do Sorteio", datetime.now().date(), key="data_sorteio_input") # .date() para pegar apenas a data

        st.subheader("Bolas Sorteadas (1 a 25)")

        # Cria 3 linhas de 5 colunas para as bolas
        bolas = []
        for row in range(3):
            cols_bolas = st.columns(5)
            for i in range(5):
                bola_index = row * 5 + i + 1
                bola_val = cols_bolas[i].number_input(
                    f"Bola {bola_index}",
                    min_value=1,
                    max_value=25,
                    step=1,
                    key=f"bola_{bola_index}_input"
                )
                bolas.append(bola_val)

        submitted = st.form_submit_button("Adicionar Concurso")

        if submitted:
            # Validar se os 15 números são únicos e válidos
            if len(set(bolas)) != 15:
                st.error("Por favor, insira 15 números únicos para as bolas sorteadas.")
            elif any(not (1 <= b <= 25) for b in bolas):
                st.error("As bolas devem ser números entre 1 e 25.")
            else:
                # Criar um DataFrame para o novo sorteio
                novo_sorteio_dict = {
                    'Concurso': int(concurso),
                    'Data Sorteio': data_sorteio.strftime("%Y-%m-%d") # <-- CORREÇÃO AQUI (Formato AAAA-MM-DD para salvar no CSV)
                }
                # Garante que as bolas estão em ordem crescente para o CSV
                bolas_ordenadas = sorted(bolas)
                for i, bola in enumerate(bolas_ordenadas):
                    novo_sorteio_dict[f'Bola{i+1}'] = bola

                novo_df = pd.DataFrame([novo_sorteio_dict])

                try:
                    salvar_novo_sorteio_oficial(novo_df)
                except Exception as e:
                    st.error(f"Erro ao salvar o concurso: {e}")

# --- ABA 4: Tabela de Preços ---
with tab4:
    st.header("Tabela de Preços da Lotofácil")
    df_precos = carregar_tabela_precos()

    if not df_precos.empty:
        st.dataframe(df_precos, use_container_width=True)
    else:
        st.warning(f"Arquivo '{ARQUIVO_TABELA_PRECO_CSV}' não encontrado ou vazio. Por favor, adicione um arquivo CSV com a tabela de preços.")

st.markdown("---")
st.markdown("Desenvolvido com ❤️ por [Marcia Romanato - BOA SORTE!]")