# -*- coding: utf-8 -*-
"""lotofacil_simulador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plUcMWehZpBahegvvfiM3_BghUt-CEBN
"""

!pip install streamlit
import streamlit as st
import random
import pandas as pd
import collections

# --- Configurações da Página ---
st.set_page_config(
    page_title="Simulador de Lotofácil",
    page_icon="🎲",
    layout="centered"
)

st.title("🎲 Simulador de Lotofácil")
st.write("Gere sorteios aleatórios e veja o histórico e estatísticas.")

# --- Inicialização do Estado da Sessão ---
# Usaremos st.session_state para manter o histórico dos sorteios
if 'historico_sorteios' not in st.session_state:
    st.session_state.historico_sorteios = []

# --- Funções do Simulador ---

def gerar_sorteio_lotofacil():
    """Gera 15 números únicos entre 1 e 25."""
    sorteio = random.sample(range(1, 26), 15)
    sorteio.sort()  # Opcional: para exibir os números em ordem crescente
    return sorteio

def adicionar_sorteio_ao_historico(sorteio):
    """Adiciona um sorteio ao histórico da sessão."""
    st.session_state.historico_sorteios.append(sorteio)

def calcular_estatisticas_simuladas():
    """Calcula a frequência de cada número nos sorteios simulados."""
    todos_numeros_sorteados = []
    for sorteio in st.session_state.historico_sorteios:
        todos_numeros_sorteados.extend(sorteio)

    if not todos_numeros_sorteados:
        return pd.DataFrame({'Número': [], 'Frequência': []})

    frequencia = collections.Counter(todos_numeros_sorteados)
    df_frequencia = pd.DataFrame(frequencia.items(), columns=['Número', 'Frequência'])
    df_frequencia = df_frequencia.sort_values(by='Frequência', ascending=False)
    return df_frequencia

# --- Layout da Aplicação Streamlit ---

# Seção de Sorteio
st.header("Gerar Novo Sorteio")
if st.button("Sortear Números"):
    novo_sorteio = gerar_sorteio_lotofacil()
    adicionar_sorteio_ao_historico(novo_sorteio)
    st.success(f"Seu sorteio gerado: **{', '.join(map(str, novo_sorteio))}**")

# Seção de Histórico
st.header("Histórico de Sorteios Simulados")
if st.session_state.historico_sorteios:
    # Exibe os últimos sorteios, ou um número limitado para não poluir a tela
    num_sorteios_para_mostrar = st.slider("Mostrar últimos X sorteios:", min_value=1, max_value=len(st.session_state.historico_sorteios), value=min(10, len(st.session_state.historico_sorteios)))

    st.write(f"Últimos {num_sorteios_para_mostrar} sorteios:")
    for i, sorteio in enumerate(reversed(st.session_state.historico_sorteios[-num_sorteios_para_mostrar:])):
        st.markdown(f"**Sorteio {len(st.session_state.historico_sorteios) - i}:** {', '.join(map(str, sorteio))}")

    if st.button("Limpar Histórico"):
        st.session_state.historico_sorteios = []
        st.success("Histórico limpo!")
        st.rerun() # Recarrega a página para refletir a mudança
else:
    st.info("Nenhum sorteio ainda. Clique em 'Sortear Números' para começar!")

# Seção de Estatísticas
st.header("Estatísticas dos Seus Sorteios Simulados")
df_estatisticas = calcular_estatisticas_simuladas()

if not df_estatisticas.empty:
    st.write("Frequência de cada número nos seus sorteios simulados:")
    st.dataframe(df_estatisticas, use_container_width=True)

    # Gráfico de barras da frequência
    st.subheader("Gráfico de Frequência")
    st.bar_chart(df_estatisticas.set_index('Número'))

    st.info(f"Total de sorteios simulados: {len(st.session_state.historico_sorteios)}")
else:
    st.info("Gere alguns sorteios para ver as estatísticas.")

st.markdown("---")
st.markdown("Desenvolvido com ❤️ por [Marcia Romanato") # Opcional: Adicione sua assinatura