# -*- coding: utf-8 -*-
"""lotofacil_simulador2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QiuKSfWRuLRSW6XLwbedMxq_PJ9yMbUl
"""

import streamlit as st
import random
import pandas as pd
import collections
from datetime import datetime

# --- Configurações da Página ---
st.set_page_config(
    page_title="Simulador de Lotofácil",
    page_icon="🎲",
    layout="centered"
)

st.title("🎲 Simulador de Lotofácil")
st.write("Gere sorteios aleatórios e veja o histórico e estatísticas.")

# --- Inicialização do Estado da Sessão ---
# O histórico agora armazenará dicionários com 'data' e 'sorteio'
if 'historico_sorteios' not in st.session_state:
    st.session_state.historico_sorteios = []

# --- Funções do Simulador ---

def gerar_sorteio_lotofacil():
    """Gera 15 números únicos entre 1 e 25."""
    sorteio = random.sample(range(1, 26), 15)
    sorteio.sort()  # Opcional: para exibir os números em ordem crescente
    return sorteio

def adicionar_sorteio_ao_historico(sorteio):
    """Adiciona um sorteio com a data atual ao histórico da sessão."""
    data_atual = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    st.session_state.historico_sorteios.append({'data': data_atual, 'sorteio': sorteio})

def calcular_estatisticas_simuladas():
    """Calcula a frequência de cada número nos sorteios simulados."""
    todos_numeros_sorteados = []
    for registro in st.session_state.historico_sorteios:
        todos_numeros_sorteados.extend(registro['sorteio'])

    if not todos_numeros_sorteados:
        return pd.DataFrame({'Número': [], 'Frequência': []})

    frequencia = collections.Counter(todos_numeros_sorteados)
    df_frequencia = pd.DataFrame(frequencia.items(), columns=['Número', 'Frequência'])
    df_frequencia = df_frequencia.sort_values(by='Frequência', ascending=False)
    return df_frequencia

# --- Layout da Aplicação Streamlit ---

# Seção de Sorteio
st.header("Gerar Novo Sorteio")
if st.button("Sortear Números"):
    novo_sorteio = gerar_sorteio_lotofacil()
    adicionar_sorteio_ao_historico(novo_sorteio)
    st.success(f"Seu sorteio gerado: **{', '.join(map(str, novo_sorteio))}**")

# Seção de Histórico e Estatísticas
# Apenas mostra as seções se houver sorteios no histórico
if st.session_state.historico_sorteios:
    st.header("Histórico de Sorteios Simulados")

    # --- AJUSTE AQUI NO SLIDER ---
    total_sorteios = len(st.session_state.historico_sorteios)
    # Garante que o max_value seja pelo menos 1 se houver sorteios
    max_slider_value = max(1, total_sorteios)
    # Garante que o valor inicial seja o mínimo entre 10 e o total de sorteios
    initial_slider_value = min(10, total_sorteios)
    # Garante que o valor inicial não seja zero se houver pelo menos um sorteio
    if initial_slider_value == 0 and total_sorteios > 0:
        initial_slider_value = 1


    num_sorteios_para_mostrar = st.slider(
        "Mostrar últimos X sorteios:",
        min_value=1, # Min_value deve ser sempre 1
        max_value=max_slider_value,
        value=initial_slider_value # Usar o valor calculado
    )
    # --- FIM DO AJUSTE NO SLIDER ---

    st.write(f"Últimos {num_sorteios_para_mostrar} sorteios:")
    # Iterar sobre os sorteios mais recentes
    for i, registro in enumerate(reversed(st.session_state.historico_sorteios[-num_sorteios_para_mostrar:])):
        st.markdown(f"**Sorteio {len(st.session_state.historico_sorteios) - i} em {registro['data']}:** {', '.join(map(str, registro['sorteio']))}")

    if st.button("Limpar Histórico"):
        st.session_state.historico_sorteios = []
        st.success("Histórico limpo!")
        st.rerun() # Recarrega a página para refletir a mudança

    st.header("Estatísticas dos Seus Sorteios Simulados")
    df_estatisticas = calcular_estatisticas_simuladas()

    if not df_estatisticas.empty:
        st.write("Frequência de cada número nos seus sorteios simulados:")
        st.dataframe(df_estatisticas, use_container_width=True)

        # Gráfico de barras da frequência
        st.subheader("Gráfico de Frequência")
        st.bar_chart(df_estatisticas.set_index('Número'))

        st.info(f"Total de sorteios simulados: {total_sorteios}")
    # Não haverá 'else' aqui, pois a seção inteira só aparece se houver sorteios

else:
    # Mensagem informativa quando não há sorteios para mostrar
    st.info("Gere seu primeiro sorteio para ver o histórico e as estatísticas!")


st.markdown("---")
st.markdown("Desenvolvido com ❤️ por [Seu Nome/Empresa]") # Opcional: Adicione sua assinatura