# -*- coding: utf-8 -*-
"""lotofacil_simulador5_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LwH5pOGYtmaqGJfgCAejkz7CR6Dle2YI
"""

import streamlit as st
import random
import pandas as pd
import collections
from datetime import datetime

# --- Configurações da Página ---
st.set_page_config(
    page_title="Simulador de Lotofácil",
    page_icon="🎲",
    layout="centered"
)

st.title("🎲 Simulador de Lotofácil")
st.write("Gere sorteios aleatórios e veja o histórico e estatísticas.")

# --- Inicialização do Estado da Sessão ---
# O histórico agora armazenará dicionários com 'data' e 'sorteio'
if 'historico_sorteios' not in st.session_state:
    st.session_state.historico_sorteios = []

# Variável para armazenar o último sorteio gerado, antes de ir para o histórico
if 'ultimo_sorteio_gerado' not in st.session_state:
    st.session_state.ultimo_sorteio_gerado = None

# --- Funções do Simulador ---

def gerar_sorteio_lotofacil():
    """Gera 15 números únicos entre 1 e 25."""
    sorteio = random.sample(range(1, 26), 15)
    sorteio.sort()  # Opcional: para exibir os números em ordem crescente
    return sorteio

def adicionar_sorteio_ao_historico(sorteio_para_adicionar):
    """
    Adiciona um sorteio ao histórico DA SESSÃO,
    mas apenas se já houver um sorteio 'anterior' no ultimo_sorteio_gerado.
    """
    if st.session_state.ultimo_sorteio_gerado is not None:
        data_anterior = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
        st.session_state.historico_sorteios.append({
            'data': data_anterior,
            'sorteio': st.session_state.ultimo_sorteio_gerado
        })
    # O sorteio recém-gerado sempre se torna o 'ultimo_sorteio_gerado' para a próxima rodada
    st.session_state.ultimo_sorteio_gerado = sorteio_para_adicionar


def calcular_estatisticas_simuladas():
    """Calcula a frequência de cada número nos sorteios simulados do histórico."""
    todos_numeros_sorteados = []
    for registro in st.session_state.historico_sorteios:
        todos_numeros_sorteados.extend(registro['sorteio'])

    if not todos_numeros_sorteados:
        return pd.DataFrame({'Número': [], 'Frequência': []})

    frequencia = collections.Counter(todos_numeros_sorteados)
    df_frequencia = pd.DataFrame(frequencia.items(), columns=['Número', 'Frequência'])
    df_frequencia = df_frequencia.sort_values(by='Frequência', ascending=False)
    return df_frequencia

# --- Layout da Aplicação Streamlit ---

# Seção de Sorteio
st.header("Gerar Novo Sorteio")
if st.button("Sortear Números"):
    # Gerar o novo sorteio
    novo_sorteio = gerar_sorteio_lotofacil()

    # Adicionar o sorteio ANTERIOR (se houver) ao histórico e atualizar o ultimo_sorteio_gerado
    adicionar_sorteio_ao_historico(novo_sorteio)

    # Exibir o sorteio ATUAL recém-gerado
    st.success(f"Seu sorteio atual: **{', '.join(map(str, novo_sorteio))}**")

# Seção de Histórico e Estatísticas
# Apenas mostra as seções se houver sorteios no histórico
if st.session_state.historico_sorteios:
    st.header("Histórico de Sorteios Simulados")

    total_sorteios = len(st.session_state.historico_sorteios)

    # --- AJUSTE CRÍTICO AQUI NO SLIDER ---
    if total_sorteios > 1: # Só mostra o slider se houver mais de um sorteio no histórico
        # Garante que o valor inicial do slider seja o mínimo entre 10 e o total de sorteios
        initial_slider_value = min(10, total_sorteios)

        num_sorteios_para_mostrar = st.slider(
            "Mostrar últimos X sorteios:",
            min_value=1,
            max_value=total_sorteios,
            value=initial_slider_value
        )
    else: # Se houver apenas 1 sorteio no histórico, não precisamos de slider
        num_sorteios_para_mostrar = 1 # Apenas exibe o único sorteio existente
    # --- FIM DO AJUSTE ---

    st.write(f"Últimos {num_sorteios_para_mostrar} sorteios registrados:")
    # Iterar sobre os sorteios mais recentes
    for i, registro in enumerate(reversed(st.session_state.historico_sorteios[-num_sorteios_para_mostrar:])):
        st.markdown(f"**Sorteio {total_sorteios - i} em {registro['data']}:** {', '.join(map(str, registro['sorteio']))}")

    if st.button("Limpar Histórico"):
        st.session_state.historico_sorteios = []
        st.session_state.ultimo_sorteio_gerado = None # Limpa o último sorteio também
        st.success("Histórico limpo!")
        st.rerun() # Recarrega a página para refletir a mudança

    st.header("Estatísticas dos Seus Sorteios Simulados")
    df_estatisticas = calcular_estatisticas_simuladas()

    if not df_estatisticas.empty:
        st.write("Frequência de cada número nos seus sorteios simulados:")
        st.dataframe(df_estatisticas, use_container_width=True)

        # Gráfico de barras da frequência
        st.subheader("Gráfico de Frequência")
        st.bar_chart(df_estatisticas.set_index('Número'))

        st.info(f"Total de sorteios históricos simulados: {total_sorteios}")
    # Não haverá 'else' aqui, pois a seção inteira só aparece se houver sorteios

else:
    # Mensagem informativa quando não há sorteios para mostrar
    st.info("O histórico começará a ser registrado a partir do segundo sorteio. Gere seu primeiro sorteio!")


st.markdown("---")
st.markdown("Desenvolvido com ❤️ por [Seu Nome/Empresa]") # Opcional: Adicione sua assinatura